# Generated by Django 5.1.5 on 2025-02-08 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Имя', 'verbose_name_plural': 'Имена'},
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='id',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='school.user'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='zoom_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], max_length=7),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.IntegerField(),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['name'], name='user_name_969ffe_idx'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
