# Generated by Django 5.1.5 on 2025-02-09 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_user_options_remove_teacher_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Бронирование', 'verbose_name_plural': 'Бронирования'},
        ),
        migrations.AlterModelOptions(
            name='officehour',
            options={'verbose_name': 'Часы приема', 'verbose_name_plural': 'Часы приема'},
        ),
        migrations.AlterModelOptions(
            name='openslot',
            options={'verbose_name': 'Открытый слот', 'verbose_name_plural': 'Открытые слоты'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Преподаватель', 'verbose_name_plural': 'Преподаватели'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='open_slot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school.openslot', verbose_name='Открытый слот'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Подтвержден'), ('cancelled', 'Отменен')], default='confirmed', max_length=50, verbose_name='Статус бронирования'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.user', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='officehour',
            name='open_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.openslot', verbose_name='Открытый слот'),
        ),
        migrations.AlterField(
            model_name='officehour',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.user', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='openslot',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='openslot',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.teacher', verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='openslot',
            name='time',
            field=models.TimeField(verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='school.user', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='zoom_url',
            field=models.URLField(verbose_name='Ссылка на Zoom'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, unique=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], max_length=7, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.IntegerField(verbose_name='Телеграм ID'),
        ),
    ]
