# Generated by Django 5.1.5 on 2025-03-27 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_teacher_photo_user_is_admin_user_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
