# Generated by Django 5.1.5 on 2025-03-27 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_remove_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
    ]
