# Generated by Django 5.1.5 on 2025-05-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_remove_user_is_admin_remove_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='level',
            field=models.CharField(default='beginner', max_length=50, verbose_name='Уровень'),
        ),
        migrations.AddField(
            model_name='booking',
            name='program',
            field=models.CharField(default='general', max_length=50, verbose_name='Программа'),
        ),
    ]
